# Site settings
author: Kyle Johnson
title: Finding Value in Overlookable Data
header-img: img/home-bg.png
email: kylejohnson1678@gmail.com
copyright_name: Kyle Johnson
description: > # this means to ignore newlines until "baseurl:"
  Using seemingly useless data as a proxy for useful data
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  kylejohnson363

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
